FROM mcr.microsoft.com/devcontainers/cpp:1-debian-12

RUN wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | gpg --dearmor > /etc/apt/trusted.gpg.d/llvm.gpg \
    && echo "deb http://apt.llvm.org/bookworm/ llvm-toolchain-bookworm-17 main" >> /etc/apt/sources.list.d/llvm.list

RUN apt-get update && export DEBIAN_FRONT_INSTALL_RECOMMENDS=1 \
    && apt-get -y install --no-install-recommends \
    build-essential \
    cmake \
    ninja-build \
    cppcheck \
    valgrind \
    clang-17 \
    clang-tidy-17 \
    clangd-17 \
    lldb-17 \
    llvm-17 \
    curl \
    gdb \
    g++ \
    git \
    pkg-config \
    libxinerama-dev \
    libxcursor-dev \
    xorg-dev \ 
    libglu1-mesa \
    libgl1-mesa-dev \
    libglfw3-dev \
    libx11-dev \
    libxcursor-dev \ 
    libxrandr-dev \
    libxinerama-dev \ 
    libxi-dev \
    x11-apps \
    && ln -s /usr/bin/clangd-17 /usr/bin/clangd \
    && apt-get autoremove -y && apt-get clean -y && rm -rf /var/lib/apt/lists/*

RUN git clone https://github.com/microsoft/vcpkg.git /opt/vcpkg \
    && /opt/vcpkg/bootstrap-vcpkg.sh