name: Build Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y cmake ninja-build build-essential libgl1-mesa-dev libx11-dev libxrandr-dev libxi-dev libasound2-dev libboost-all-dev

    - name: Configure CMake
      run: cmake --preset ninja

    - name: Build Release
      run: cmake --build --preset release

    - name: Upload binary
      uses: actions/upload-artifact@v3
      with:
        name: kaban-release
        path: ./build/app/Release/kaban
